---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-pod-identity-webhook
  namespace: klearwave-identity-system # +operator-builder:field:name=namespace,default="klearwave-identity-system",type=string
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aws-pod-identity-webhook
  namespace: klearwave-identity-system # +operator-builder:field:name=namespace,default="klearwave-identity-system",type=string
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - update
      - patch
    resourceNames:
      - pod-identity-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-pod-identity-webhook
  namespace: klearwave-identity-system # +operator-builder:field:name=namespace,default="klearwave-identity-system",type=string
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-pod-identity-webhook
subjects:
  - kind: ServiceAccount
    name: aws-pod-identity-webhook
    namespace: klearwave-identity-system # +operator-builder:field:name=namespace,default="klearwave-identity-system",type=string
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-pod-identity-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-pod-identity-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-pod-identity-webhook
subjects:
  - kind: ServiceAccount
    name: aws-pod-identity-webhook
    namespace: klearwave-identity-system # +operator-builder:field:name=namespace,default="klearwave-identity-system",type=string
