---
apiVersion: v1
kind: Service
metadata:
  name: aws-pod-identity-webhook
  namespace: klearwave-identity-system # +operator-builder:field:name=namespace,default="klearwave-identity-system",type=string
  annotations:
    prometheus.io/port: "9443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app: pod-identity-webhook
    platform.klearwave.io/capability: identity
    platform.klearwave.io/component: aws-pod-identity-webhook
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
