---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: trust-manager
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
  name: trust-manager
rules:
  - apiGroups:
      - trust.cert-manager.io
    resources:
      - bundles
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - trust.cert-manager.io
    resources:
      - bundles/finalizers
    verbs:
      - update
  - apiGroups:
      - trust.cert-manager.io
    resources:
      - bundles/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
  name: trust-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trust-manager
subjects:
  - kind: ServiceAccount
    name: trust-manager
    namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trust-manager
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trust-manager:leaderelection
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
      - watch
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trust-manager
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trust-manager
subjects:
  - kind: ServiceAccount
    name: trust-manager
    namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trust-manager:leaderelection
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trust-manager:leaderelection
subjects:
  - kind: ServiceAccount
    name: trust-manager
    namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
