apiVersion: v1
kind: Service
metadata:
  name: trust-manager-metrics
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  ports:
    - port: 9402
      targetPort: 9402
      protocol: TCP
      name: metrics
  selector:
    app: trust-manager
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
---
apiVersion: v1
kind: Service
metadata:
  name: trust-manager
  namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 6443
      protocol: TCP
      name: webhook
  selector:
    app: trust-manager
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
