apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: trust-manager
  labels:
    app.kubernetes.io/name: trust-manager
    app.kubernetes.io/version: v0.17.1
    app.kubernetes.io/managed-by: certificates-operator
    platform.klearwave.io/capability: certificates
    platform.klearwave.io/component: trust-manager
    platform.klearwave.io/operator-version: unstable
    platform.klearwave.io/platform-version: unstable
    app.kubernetes.io/part-of: platform
  annotations:
    # +operator-builder:field:name=namespace,type=string,replace="klearwave-certificates-system"
    cert-manager.io/inject-ca-from: klearwave-certificates-system/trust-manager-cert
webhooks:
  - name: trust.cert-manager.io
    rules:
      - apiGroups:
          - trust.cert-manager.io
        apiVersions:
          - '*'
        operations:
          - CREATE
          - UPDATE
        resources:
          - '*/*'
    admissionReviewVersions:
      - v1
    timeoutSeconds: 5
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        name: trust-manager
        namespace: klearwave-certificates-system # +operator-builder:field:name=namespace,default="klearwave-certificates-system",type=string
        path: /validate-trust-cert-manager-io-v1alpha1-bundle
