---
commonOverlays:
  - name: "add common labels"
    query:
      - metadata.labels
    action: merge
    value:
      platform.klearwave.io/capability: "{{ .capability }}"
      platform.klearwave.io/component: "{{ .component }}"
      platform.klearwave.io/operator-version: "{{ .operatorVersion }}"
      platform.klearwave.io/platform-version: "{{ .platformVersion }}"
      app.kubernetes.io/part-of: platform
      app.kubernetes.io/managed-by: certificates-operator

  - name: "remove redundant labels and potential helm data"
    query: 
      - metadata.labels["helm.sh/chart"]
      - spec.template.metadata.labels["helm.sh/chart"]
      - metadata.annotations["helm.sh/resource-policy"]
      - metadata.labels["app"]
      - metadata.labels["app.kubernetes.io/instance"]
      - metadata.labels["app.kubernetes.io/component"]
      - spec.template.metadata.labels["app"]
      - spec.template.metadata.labels["app.kubernetes.io/instance"]
      - spec.template.metadata.labels["app.kubernetes.io/component"]
      - spec.selector.matchLabels["app"]
      - spec.selector.matchLabels["app.kubernetes.io/instance"]
      - spec.selector.matchLabels["app.kubernetes.io/component"]
      - spec.selector["app.kubernetes.io/instance"]
      - spec.selector["app.kubernetes.io/component"]
    action: delete

yamlFiles:
  - name: "trust-manager certificates"
    path: "../../vendor/trust-manager.yaml"
    outputPath: "certificates/trust-manager/certificates.yaml"
    overlays:
      - name: "ensure we are only acting upon certificate resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "Certificate")]

      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .defaultNamespace }}"

      - name: "ensure name is updated appropriately"
        query: metadata.name
        value: trust-manager

      - name: "ensure issuer name is used correctly"
        query: spec.issuerRef
        action: replace
        value: 
          name: "internal"
          kind: "ClusterIssuer"

      - name: "ensure secret name is used correctly"
        query: spec.secretName
        action: replace
        value: "trust-manager-cert"

      - name: "ensure certificate common name generated correctly"
        query: spec.commonName
        action: replace
        value: "trust-manager.{{ .defaultNamespace }}.svc"

      - name: "ensure certificate dns name generated correctly"
        documentQuery:
          - conditions:
              - query: $[?($.kind == "Certificate")]
        query: spec.dnsNames
        action: replace
        value:
          - "trust-manager"
          - "trust-manager.{{ .defaultNamespace }}"
          - "trust-manager.{{ .defaultNamespace }}.svc"
          - "trust-manager.{{ .defaultNamespace }}.svc.local"
