---
defaultNamespace: klearwave-certificates-system
component: trust-manager
projectVersion: v0.9.2
operatorVersion: unstable
platformVersion: unstable
controller:
  replicas: 1
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      memory: "64Mi"