---
commonOverlays:
  - name: "add common labels"
    query:
      - metadata.labels
    action: merge
    value:
      platform.klearwave.io/capability: "{{ .capability }}"
      platform.klearwave.io/component: "{{ .component }}"
      platform.klearwave.io/operator-version: "{{ .operatorVersion }}"
      platform.klearwave.io/platform-version: "{{ .platformVersion }}"
      app.kubernetes.io/version: "{{ .projectVersion }}"
      app.kubernetes.io/part-of: platform
      app.kubernetes.io/managed-by: certificates-operator

  - name: "add namespace markers"
    query:
      - metadata.namespace
      - subjects[*].namespace
      - "webhooks[*].clientConfig.service.namespace"
    value: "{{ .defaultNamespace }}"  # +operator-builder:field:name=namespace,default="{{ .defaultNamespace }}",type=string

yamlFiles:
  - name: "cert-manager webhooks"
    path: "../../vendor/cert-manager.yaml"
    outputPath: "certificates/cert-manager/webhook.yaml"
    overlays:
      - name: "ensure we are only acting upon webhook resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "ValidatingWebhookConfiguration")]
              - query: $[?($.kind != "MutatingWebhookConfiguration")]

      - name: "set namespace in CA reference annotation"
        query: "metadata.annotations"
        value:
          # +operator-builder:field:name=namespace,type=string,replace="certs-namespace"
          cert-manager.io/inject-ca-from-secret: certs-namespace/cert-manager-webhook-ca
