---
component: cert-manager
defaultNamespace: kw-certificates-system
projectVersion: v1.17.2
injector:
  replicas: 2
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      memory: "128Mi"
controller:
  replicas: 1
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      memory: "64Mi"
webhook:
  replicas: 2
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      memory: "64Mi"

