kind: StandaloneWorkload
name: cert-manager
spec:
  api:
    clusterScoped: true
    domain: platform.klearwave.io
    group: certificates
    kind: CertManager
    version: v1alpha1
  companionCliRootcmd:
    name: certificatesctl
    description: Manage the certificates capability
  resources:
    - ../manifests/crds.yaml
    - ../manifests/rbac.yaml
    - ../manifests/deployment.yaml
    - ../manifests/service.yaml
    - ../static/issuer-internal.yaml
    - ../manifests/webhook.yaml
