---
commonOverlays:
  - name: "add common labels"
    query:
      - metadata.labels
    action: merge
    value:
      platform.klearwave.io/capability: "{{ .capability }}"
      platform.klearwave.io/component: "{{ .component }}"
      platform.klearwave.io/operator-version: "{{ .operatorVersion }}"
      platform.klearwave.io/platform-version: "{{ .platformVersion }}"
      app.kubernetes.io/part-of: platform
      app.kubernetes.io/managed-by: certificates-operator

  - name: "remove redundant labels and potential helm data"
    query: 
      - metadata.labels["helm.sh/chart"]
      - spec.template.metadata.labels["helm.sh/chart"]
      - metadata.annotations["helm.sh/resource-policy"]
      - metadata.labels["app"]
      - metadata.labels["app.kubernetes.io/instance"]
      - metadata.labels["app.kubernetes.io/component"]
      - spec.template.metadata.labels["app"]
      - spec.template.metadata.labels["app.kubernetes.io/instance"]
      - spec.template.metadata.labels["app.kubernetes.io/component"]
      - spec.selector.matchLabels["app"]
      - spec.selector.matchLabels["app.kubernetes.io/instance"]
      - spec.selector.matchLabels["app.kubernetes.io/component"]
      - spec.selector["app.kubernetes.io/instance"]
      - spec.selector["app.kubernetes.io/component"]
    action: delete

  - name: "add namespace markers"
    query:
      - metadata.namespace
      - "webhooks[*].clientConfig.service.namespace"
    value: "{{ .defaultNamespace }}"  # +operator-builder:field:name=namespace,default="{{ .defaultNamespace }}",type=string

  - name: "set the name to prefix with aws"
    query: metadata.name
    value: "{{ .component }}"
    action: replace

yamlFiles:
  - name: "aws-pod-identity-webhook webhooks"
    path: "../../vendor/mutatingwebhook.yaml"
    outputPath: "identity/aws-pod-identity-webhook/webhook.yaml"
    overlays:
      - name: "ensure we are only acting upon webhook resources"
        query: "$"
        action: delete
        documentQuery:
          - conditions:
              - query: $[?($.kind != "ValidatingWebhookConfiguration")]
              - query: $[?($.kind != "MutatingWebhookConfiguration")]

      - name: "set namespace in CA reference annotation"
        query: "metadata.annotations"
        value:
          # +operator-builder:field:name=namespace,type=string,replace="{{ .defaultNamespace }}"
          cert-manager.io/inject-ca-from: "{{ .defaultNamespace }}/{{ .component }}-cert"

      - name: "ensure name is updated"
        query:
          - webhooks[0].clientConfig.service.name
        value: "{{ .component }}"
